### ISSUE TITLE
Revise environment.yml file to remove taxcalc pinning

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Behavioral-Responses#49]
Now the `environment.yml` file has these contents:
```
name: behresp-dev
channels:
- PSLmodels
dependencies:
- python
- "taxcalc>=1.0"
```
After a period of time (and everybody is using taxcalc 1.0+), the last line above should be changed to:
```
- taxcalc
```
This change will make it easier to create for testing a local `behresp` package that uses a local `taxcalc` package, which is version 0.0.0.

**Comment by hdoupe** [comment]
@martinholmer, I just have a side comment on #49. I've found it helpful to have the version hard coded in the init file. I then update it on each release. This makes it easy to verify that your local version is up to date. This is pertinent when you are working on a couple packages that depend on each other and you are doing some development work on them simultaneously or doing some preliminary testing of one package with the other package. The latter case sounds similar to the problem that you are having here. The downside of hard coding the version is that you have to remember to bump the version on each release.

**Comment by martinholmer** [comment]
@hdoupe said:
> I just have a side comment on #49. I've found it helpful to have the version hard coded in the init file. I then update it on each release.

Thanks for the tip!  Do you mean by "the init file" the `envioronment.yml` file or some other file?

**Comment by hdoupe** [comment]
Sure thing. I mean `__init__.py`. For example: https://github.com/PSLmodels/ParamTools/blob/master/paramtools/__init__.py#L34

**Comment by martinholmer** [comment]
@hdoupe said:
> I mean __init__.py
OK.  I understand what you're saying.  Thanks for the thought.
