### ISSUE TITLE
Suggestion regarding python versions

### ISSUE THREAD

**Issue by kpomerleau** [PSLmodels/Behavioral-Responses#73]
I ran into an issue when installing behresp to my personal computer. Specifically, it is incompatible with Python 3.8. Ultimately, I got everything to work by setting the python version in taxcalc virtual environment to 3.7.

I don't know what the best practices are with respect to python versions, but it might be worth while to either 1) update behresp to work with the newest version or 2) instruct users in how to set their python version so that everything works.

**Comment by hdoupe** [comment]
Thanks for opening this issue @kpomerleau. I don't think Tax-Calculator is tested on Python 3.8 either. I'll update Tax-Calculator to work with Python 3.8 and then will update Behavioral-Responses after that.

cc @MattHJensen @Peter-Metz
