### ISSUE TITLE
"No module named 'behresp'" in Colab

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Behavioral-Responses#77]
After installing `behresp` in Colab using the below commands ([notebook](https://colab.research.google.com/drive/1JZRCUr_Nfzte-xtypd7sRqLv8NneuCIl?usp=sharing#scrollTo=3p-xyioIIqrr)), `import behresp` fails:
```
!wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -bfp /usr/local
# Append path to be able to run packages installed with conda
import sys
# This must correspond to the conda Python version, which may differ from
# the base Colab Python installation.
sys.path.append('/usr/local/lib/python3.8/site-packages')
# Install PSL packages from Anaconda
!yes | conda install -c conda-forge paramtools
!yes | conda install -c PSLmodels taxcalc behresp
```
>...
The following NEW packages will be INSTALLED:
...
  behresp            PSLmodels/linux-64::behresp-0.11.0-py38_0
...
```
import taxcalc  # No error.
```
```
import behresp
```
>ModuleNotFoundError: No module named 'behresp'

This works fine when I run in a new conda environment locally.

**Comment by jdebacker** [comment]
@MaxGhenis Do you still find this issue when installing `behresp` from conda-forge?

**Comment by MaxGhenis** [comment]
Works now! Here's the [notebook](https://colab.research.google.com/drive/1JZRCUr_Nfzte-xtypd7sRqLv8NneuCIl).

**Comment by jdebacker** [comment]
Excellent - thanks for confirming.
