### ISSUE TITLE
Trouble installing version 0.11.0

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Behavioral-Responses#78]
I'm trying to install the latest version and running into some trouble. It seems like conda thinks this version can't be installed with python versions above 3.5. I've attached a screen shot with the error message I get.
<img width="614" alt="Screen Shot 2020-10-05 at 5 04 11 PM" src="https://user-images.githubusercontent.com/20684675/95131859-cb8e7b00-072c-11eb-8184-a56cdc16bc82.png">

Version 0.10.0 works as expected for up to python 3.7.

I was looking through the latest PRs and the various set up files and I have no idea what could be causing the issues here. I'll keep trying and see if I can find anything.

cc @MattHJensen @jdebacker

**Comment by jdebacker** [comment]
@andersonfrailey What version of `taxcalc` do you have in this environment?

**Comment by andersonfrailey** [comment]
@jdebacker I was trying to install it in a new environment without taxcalc that time. But I just tried updating to taxcalc 3.0 and am getting the same error so It might just be an issue with my conda install. When I get a little more free time I'll try wiping everything and giving it another go.

**Comment by jdebacker** [comment]
@andersonfrailey report back if that doesn't work.  I had some similar issue the other day, but I thought upgrading TC did the trick, though I can't remember for sure.

**Comment by andersonfrailey** [comment]
@jdebacker, just finished uninstalling and reinstalling python. Still no luck. I've set up environments with python 3.7 and 3.8 and conda won't allow me to install taxcalc 3.0. It's telling me that there is no taxcalc package that supports either version, just like it was doing for behresp last night. But if you and others have been able to successfully install those versions it's probably just an issue on my end I need to troubleshoot.

**Comment by andersonfrailey** [comment]
Update. I just reinstalled the taxbrain-dev conda environment and it was created with taxcalc 3.0, behresp 0.11, and python 3.8. I still have no clue why I was having trouble earlier, but it seems like this is just a personal issue so I'm going to go ahead and close this.

**Comment by jdebacker** [comment]
@andersonfrailey Glad to hear you got it - and it's not just you.  Like I said, I had the same issue and can't remember how I solved it, but it was probably just what you did - rebuilt the environment.
