### ISSUE TITLE
Adding Behavioral-Responses to Conda-Forge

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Behavioral-Responses#79]
I'm trying to release Tax-Brain on Conda-Forge, but, according to [this document](https://conda-forge.org/docs/maintainer/adding_pkgs.html#avoid-external-dependencies), all dependencies need to also be on conda-forge so the build won't work until we get Behavioral-Responses up there too.

**Comment by hdoupe** [comment]
Agreed @andersonfrailey. I know a few others like @jdebacker and @chusloj have recently added packages to conda-forge.

**Comment by chusloj** [comment]
@andersonfrailey @hdoupe I open a PR for behavioral responses in `Conda-forge` today.

**Comment by andersonfrailey** [comment]
Awesome, thanks, @chusloj!

**Comment by chusloj** [comment]
`behresp` is now live on `conda-forge`: https://github.com/conda-forge/behresp-feedstock

**Comment by hdoupe** [comment]
You're the man @chusloj! Thanks for setting that up.

**Comment by andersonfrailey** [comment]
Thanks @chusloj! Closing.
